# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test # DO NOT RE-ADD THIS, THIS ASSUMES THE DB IS RUNNING LOCALLY


quarkus.http.auth.proactive=false

# JDBC configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# Hibernate configuration
quarkus.hibernate-orm.database.generation=drop-and-create
# quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=false