#quarkus.datasource.username=quarkus_test
#quarkus.datasource.password=quarkus_test
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_test

quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
# quarkus.hibernate-orm.sql-load-script=import.sql


#testcontainers.reuse.enable=true
quarkus.datasource.devservices.reuse=true


quarkus.http.auth.proactive=false